export type {
  AssociationAnnotation,
  AssociationEvidence,
  AssociationSearchResult as MeilisearchAssociation,
  CvTermReference,
  IdentifierEntry,
  InteractionAnnotation,
  InteractionDirection,
  InteractionEvidence,
  InteractionSearchResponse as MeilisearchSearchResponse,
  InteractionSearchResult as MeilisearchInteraction,
  SearchFilters as MeilisearchFilters,
  SearchParams as MeilisearchSearchParams,
  SearchSource as MeilisearchSource,
  SourceFunctionRecord as MeilisearchSourceFunctionRecord,
} from '@/types/search';
