-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "django_migrations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_migrations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"app" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"applied" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "reference" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reference_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pubmed_id" bigint,
	"doi" varchar(255),
	CONSTRAINT "unique_reference_pubmed_id" UNIQUE("pubmed_id"),
	CONSTRAINT "unique_reference_doi" UNIQUE("doi")
);
--> statement-breakpoint
CREATE TABLE "interaction_evidence" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "interaction_evidence_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"evidence_sentence" text,
	"source_identifier" varchar(255),
	"is_directed" boolean NOT NULL,
	"direction" varchar(10),
	"sign" varchar(10),
	"causal_mechanism_id" integer,
	"causal_statement_id" integer,
	"data_source_id" integer NOT NULL,
	"interaction_id" integer NOT NULL,
	"interaction_type_id" integer,
	"reference_id" integer,
	CONSTRAINT "interaction_evidence_source_identifier_key" UNIQUE("source_identifier"),
	CONSTRAINT "unique_interaction_evidence_source_identifier" UNIQUE("source_identifier")
);
--> statement-breakpoint
CREATE TABLE "cv_namespace" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cv_namespace_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"description" text,
	"reference_id" integer,
	CONSTRAINT "cv_namespace_name_key" UNIQUE("name"),
	CONSTRAINT "unique_namespace" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "cv_term" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cv_term_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"accession" varchar(100) NOT NULL,
	"name" varchar(255) NOT NULL,
	"definition" text,
	"is_obsolete" boolean NOT NULL,
	"comment" text,
	"category_id" integer,
	"namespace_id" integer NOT NULL,
	"replaced_by_id" integer,
	CONSTRAINT "unique_cv_term" UNIQUE("accession")
);
--> statement-breakpoint
CREATE TABLE "cv_term_is_a" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cv_term_is_a_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"from_controlledvocabularyterm_id" integer NOT NULL,
	"to_controlledvocabularyterm_id" integer NOT NULL,
	CONSTRAINT "cv_term_is_a_from_controlledvocabular_7115ab7d_uniq" UNIQUE("from_controlledvocabularyterm_id","to_controlledvocabularyterm_id")
);
--> statement-breakpoint
CREATE TABLE "entity" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "entity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text,
	"canonical_identifier" varchar(255) NOT NULL,
	"canonical_identifier_type_id" integer,
	"entity_type_id" integer NOT NULL,
	"ncbi_tax_id_id" integer,
	CONSTRAINT "unique_entity_ncbi_tax_id_canonical_identifier" UNIQUE("canonical_identifier")
);
--> statement-breakpoint
CREATE TABLE "entity_cv_terms" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "entity_cv_terms_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"entity_id" integer NOT NULL,
	"controlledvocabularyterm_id" integer NOT NULL,
	CONSTRAINT "entity_cv_terms_entity_id_controlledvoca_491a7d6d_uniq" UNIQUE("entity_id","controlledvocabularyterm_id")
);
--> statement-breakpoint
CREATE TABLE "entity_identifier" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "entity_identifier_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"value" varchar(255) NOT NULL,
	"entity_id" integer NOT NULL,
	"identifier_type_id" integer NOT NULL,
	CONSTRAINT "uniq_entity_identifier" UNIQUE("value","entity_id","identifier_type_id")
);
--> statement-breakpoint
CREATE TABLE "entity_membership" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "entity_membership_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"stoichiometry" integer,
	"member_entity_id" integer NOT NULL,
	"parent_entity_id" integer NOT NULL,
	CONSTRAINT "unique_entity_membership" UNIQUE("member_entity_id","parent_entity_id")
);
--> statement-breakpoint
CREATE TABLE "interaction" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "interaction_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"entity_a_id" integer NOT NULL,
	"entity_b_id" integer NOT NULL,
	CONSTRAINT "unique_interaction_entities" UNIQUE("entity_a_id","entity_b_id")
);
--> statement-breakpoint
CREATE TABLE "interaction_evidence_detection_methods" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "interaction_evidence_detection_methods_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"interactionevidence_id" integer NOT NULL,
	"controlledvocabularyterm_id" integer NOT NULL,
	CONSTRAINT "interaction_evidence_det_interactionevidence_id_c_51a18c37_uniq" UNIQUE("interactionevidence_id","controlledvocabularyterm_id")
);
--> statement-breakpoint
CREATE TABLE "interaction_participant" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "interaction_participant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"stoichiometry" integer,
	"features" text,
	"annotations" text,
	"entity_id" integer NOT NULL,
	"interaction_evidence_id" integer NOT NULL,
	CONSTRAINT "unique_interaction_participant" UNIQUE("entity_id","interaction_evidence_id"),
	CONSTRAINT "interaction_participant_stoichiometry_check" CHECK (stoichiometry >= 0)
);
--> statement-breakpoint
CREATE TABLE "interaction_participant_biological_roles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "interaction_participant_biological_roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"interactionparticipant_id" integer NOT NULL,
	"controlledvocabularyterm_id" integer NOT NULL,
	CONSTRAINT "interaction_participant__interactionparticipant_i_12780ea2_uniq" UNIQUE("interactionparticipant_id","controlledvocabularyterm_id")
);
--> statement-breakpoint
CREATE TABLE "interaction_participant_experimental_roles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "interaction_participant_experimental_roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"interactionparticipant_id" integer NOT NULL,
	"controlledvocabularyterm_id" integer NOT NULL,
	CONSTRAINT "interaction_participant__interactionparticipant_i_de28e281_uniq" UNIQUE("interactionparticipant_id","controlledvocabularyterm_id")
);
--> statement-breakpoint
CREATE TABLE "interaction_participant_interactor_types" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "interaction_participant_interactor_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"interactionparticipant_id" integer NOT NULL,
	"controlledvocabularyterm_id" integer NOT NULL,
	CONSTRAINT "interaction_participant__interactionparticipant_i_b6a1062c_uniq" UNIQUE("interactionparticipant_id","controlledvocabularyterm_id")
);
--> statement-breakpoint
CREATE TABLE "protein_details" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "protein_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sequence_length" integer,
	"molecular_weight" double precision,
	"entity_id" integer NOT NULL,
	CONSTRAINT "unique_protein_detail_entity" UNIQUE("entity_id")
);
--> statement-breakpoint
CREATE TABLE "cv_term_references" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cv_term_references_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"controlledvocabularyterm_id" integer NOT NULL,
	"reference_id" integer NOT NULL,
	CONSTRAINT "cv_term_references_controlledvocabularyterm_3f445e11_uniq" UNIQUE("controlledvocabularyterm_id","reference_id")
);
--> statement-breakpoint
CREATE TABLE "cv_term_synonym" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cv_term_synonym_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"synonym" varchar(512) NOT NULL,
	"term_id" integer NOT NULL,
	CONSTRAINT "unique_cv_term_synonym" UNIQUE("synonym","term_id")
);
--> statement-breakpoint
ALTER TABLE "interaction_evidence" ADD CONSTRAINT "interaction_evidence_reference_id_c90cd0be_fk_reference_id" FOREIGN KEY ("reference_id") REFERENCES "public"."reference"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_evidence" ADD CONSTRAINT "interaction_evidence_causal_mechanism_id_fdf31745_fk_cv_term_id" FOREIGN KEY ("causal_mechanism_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_evidence" ADD CONSTRAINT "interaction_evidence_causal_statement_id_b53eb7f8_fk_cv_term_id" FOREIGN KEY ("causal_statement_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_evidence" ADD CONSTRAINT "interaction_evidence_data_source_id_b8c0f36d_fk_cv_term_id" FOREIGN KEY ("data_source_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_evidence" ADD CONSTRAINT "interaction_evidence_interaction_id_80b07c95_fk_interaction_id" FOREIGN KEY ("interaction_id") REFERENCES "public"."interaction"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_evidence" ADD CONSTRAINT "interaction_evidence_interaction_type_id_f7dc5348_fk_cv_term_id" FOREIGN KEY ("interaction_type_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cv_namespace" ADD CONSTRAINT "cv_namespace_reference_id_6a1327db_fk_reference_id" FOREIGN KEY ("reference_id") REFERENCES "public"."reference"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cv_term" ADD CONSTRAINT "cv_term_category_id_2610ead9_fk_cv_term_id" FOREIGN KEY ("category_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cv_term" ADD CONSTRAINT "cv_term_namespace_id_6fab6e10_fk_cv_namespace_id" FOREIGN KEY ("namespace_id") REFERENCES "public"."cv_namespace"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cv_term" ADD CONSTRAINT "cv_term_replaced_by_id_780fd6c0_fk_cv_term_id" FOREIGN KEY ("replaced_by_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cv_term_is_a" ADD CONSTRAINT "cv_term_is_a_from_controlledvocab_77de1043_fk_cv_term_i" FOREIGN KEY ("from_controlledvocabularyterm_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cv_term_is_a" ADD CONSTRAINT "cv_term_is_a_to_controlledvocabul_416e14c0_fk_cv_term_i" FOREIGN KEY ("to_controlledvocabularyterm_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity" ADD CONSTRAINT "entity_canonical_identifier_type_id_472aea07_fk_cv_term_id" FOREIGN KEY ("canonical_identifier_type_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity" ADD CONSTRAINT "entity_entity_type_id_20fad4cd_fk_cv_term_id" FOREIGN KEY ("entity_type_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity" ADD CONSTRAINT "entity_ncbi_tax_id_id_62c4f39b_fk_cv_term_id" FOREIGN KEY ("ncbi_tax_id_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity_cv_terms" ADD CONSTRAINT "entity_cv_terms_entity_id_ab7ea1ab_fk_entity_id" FOREIGN KEY ("entity_id") REFERENCES "public"."entity"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity_cv_terms" ADD CONSTRAINT "entity_cv_terms_controlledvocabulary_187bc697_fk_cv_term_i" FOREIGN KEY ("controlledvocabularyterm_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity_identifier" ADD CONSTRAINT "entity_identifier_entity_id_5aa1b337_fk_entity_id" FOREIGN KEY ("entity_id") REFERENCES "public"."entity"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity_identifier" ADD CONSTRAINT "entity_identifier_identifier_type_id_723986c8_fk_cv_term_id" FOREIGN KEY ("identifier_type_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity_membership" ADD CONSTRAINT "entity_membership_member_entity_id_7a73e1f7_fk_entity_id" FOREIGN KEY ("member_entity_id") REFERENCES "public"."entity"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity_membership" ADD CONSTRAINT "entity_membership_parent_entity_id_6fa801d1_fk_entity_id" FOREIGN KEY ("parent_entity_id") REFERENCES "public"."entity"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction" ADD CONSTRAINT "interaction_entity_a_id_1e01695d_fk_entity_id" FOREIGN KEY ("entity_a_id") REFERENCES "public"."entity"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction" ADD CONSTRAINT "interaction_entity_b_id_c3fc492d_fk_entity_id" FOREIGN KEY ("entity_b_id") REFERENCES "public"."entity"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_evidence_detection_methods" ADD CONSTRAINT "interaction_evidence_interactionevidence__e398231b_fk_interacti" FOREIGN KEY ("interactionevidence_id") REFERENCES "public"."interaction_evidence"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_evidence_detection_methods" ADD CONSTRAINT "interaction_evidence_controlledvocabulary_74a05f78_fk_cv_term_i" FOREIGN KEY ("controlledvocabularyterm_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_participant" ADD CONSTRAINT "interaction_participant_entity_id_7a25c0ab_fk_entity_id" FOREIGN KEY ("entity_id") REFERENCES "public"."entity"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_participant" ADD CONSTRAINT "interaction_particip_interaction_evidence_174be63c_fk_interacti" FOREIGN KEY ("interaction_evidence_id") REFERENCES "public"."interaction_evidence"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_participant_biological_roles" ADD CONSTRAINT "interaction_particip_interactionparticipa_c1b98d91_fk_interacti" FOREIGN KEY ("interactionparticipant_id") REFERENCES "public"."interaction_participant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_participant_biological_roles" ADD CONSTRAINT "interaction_particip_controlledvocabulary_98df8d38_fk_cv_term_i" FOREIGN KEY ("controlledvocabularyterm_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_participant_experimental_roles" ADD CONSTRAINT "interaction_particip_interactionparticipa_1a3bbdde_fk_interacti" FOREIGN KEY ("interactionparticipant_id") REFERENCES "public"."interaction_participant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_participant_experimental_roles" ADD CONSTRAINT "interaction_particip_controlledvocabulary_c6e6b07c_fk_cv_term_i" FOREIGN KEY ("controlledvocabularyterm_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_participant_interactor_types" ADD CONSTRAINT "interaction_particip_interactionparticipa_0b95ae8d_fk_interacti" FOREIGN KEY ("interactionparticipant_id") REFERENCES "public"."interaction_participant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_participant_interactor_types" ADD CONSTRAINT "interaction_particip_controlledvocabulary_ba68e8dd_fk_cv_term_i" FOREIGN KEY ("controlledvocabularyterm_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "protein_details" ADD CONSTRAINT "protein_details_entity_id_1d05a0aa_fk_entity_id" FOREIGN KEY ("entity_id") REFERENCES "public"."entity"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cv_term_references" ADD CONSTRAINT "cv_term_references_controlledvocabulary_846e2892_fk_cv_term_i" FOREIGN KEY ("controlledvocabularyterm_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cv_term_references" ADD CONSTRAINT "cv_term_references_reference_id_cc691283_fk_reference_id" FOREIGN KEY ("reference_id") REFERENCES "public"."reference"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cv_term_synonym" ADD CONSTRAINT "cv_term_synonym_term_id_e0262e90_fk_cv_term_id" FOREIGN KEY ("term_id") REFERENCES "public"."cv_term"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "reference_doi_294344b0_like" ON "reference" USING btree ("doi" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "interaction_evidence_causal_mechanism_id_fdf31745" ON "interaction_evidence" USING btree ("causal_mechanism_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_evidence_causal_statement_id_b53eb7f8" ON "interaction_evidence" USING btree ("causal_statement_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_evidence_data_source_id_b8c0f36d" ON "interaction_evidence" USING btree ("data_source_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_evidence_interaction_id_80b07c95" ON "interaction_evidence" USING btree ("interaction_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_evidence_interaction_type_id_f7dc5348" ON "interaction_evidence" USING btree ("interaction_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_evidence_reference_id_c90cd0be" ON "interaction_evidence" USING btree ("reference_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_evidence_source_identifier_a2009405_like" ON "interaction_evidence" USING btree ("source_identifier" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "cv_namespace_name_1ba4fd70_like" ON "cv_namespace" USING btree ("name" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "cv_namespace_reference_id_6a1327db" ON "cv_namespace" USING btree ("reference_id" int4_ops);--> statement-breakpoint
CREATE INDEX "cv_term_category_id_2610ead9" ON "cv_term" USING btree ("category_id" int4_ops);--> statement-breakpoint
CREATE INDEX "cv_term_namespace_id_6fab6e10" ON "cv_term" USING btree ("namespace_id" int4_ops);--> statement-breakpoint
CREATE INDEX "cv_term_replaced_by_id_780fd6c0" ON "cv_term" USING btree ("replaced_by_id" int4_ops);--> statement-breakpoint
CREATE INDEX "cv_term_is_a_from_controlledvocabularyterm_id_77de1043" ON "cv_term_is_a" USING btree ("from_controlledvocabularyterm_id" int4_ops);--> statement-breakpoint
CREATE INDEX "cv_term_is_a_to_controlledvocabularyterm_id_416e14c0" ON "cv_term_is_a" USING btree ("to_controlledvocabularyterm_id" int4_ops);--> statement-breakpoint
CREATE INDEX "entity_canonical_identifier_type_id_472aea07" ON "entity" USING btree ("canonical_identifier_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "entity_entity_type_id_20fad4cd" ON "entity" USING btree ("entity_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "entity_ncbi_tax_id_id_62c4f39b" ON "entity" USING btree ("ncbi_tax_id_id" int4_ops);--> statement-breakpoint
CREATE INDEX "entity_cv_terms_controlledvocabularyterm_id_187bc697" ON "entity_cv_terms" USING btree ("controlledvocabularyterm_id" int4_ops);--> statement-breakpoint
CREATE INDEX "entity_cv_terms_entity_id_ab7ea1ab" ON "entity_cv_terms" USING btree ("entity_id" int4_ops);--> statement-breakpoint
CREATE INDEX "entity_identifier_entity_id_5aa1b337" ON "entity_identifier" USING btree ("entity_id" int4_ops);--> statement-breakpoint
CREATE INDEX "entity_identifier_identifier_type_id_723986c8" ON "entity_identifier" USING btree ("identifier_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "entity_membership_member_entity_id_7a73e1f7" ON "entity_membership" USING btree ("member_entity_id" int4_ops);--> statement-breakpoint
CREATE INDEX "entity_membership_parent_entity_id_6fa801d1" ON "entity_membership" USING btree ("parent_entity_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_entity_a_id_1e01695d" ON "interaction" USING btree ("entity_a_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_entity_b_id_c3fc492d" ON "interaction" USING btree ("entity_b_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_evidence_detec_controlledvocabularyterm_i_74a05f78" ON "interaction_evidence_detection_methods" USING btree ("controlledvocabularyterm_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_evidence_detec_interactionevidence_id_e398231b" ON "interaction_evidence_detection_methods" USING btree ("interactionevidence_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_participant_entity_id_7a25c0ab" ON "interaction_participant" USING btree ("entity_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_participant_interaction_evidence_id_174be63c" ON "interaction_participant" USING btree ("interaction_evidence_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_participant_bi_controlledvocabularyterm_i_98df8d38" ON "interaction_participant_biological_roles" USING btree ("controlledvocabularyterm_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_participant_bi_interactionparticipant_id_c1b98d91" ON "interaction_participant_biological_roles" USING btree ("interactionparticipant_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_participant_ex_controlledvocabularyterm_i_c6e6b07c" ON "interaction_participant_experimental_roles" USING btree ("controlledvocabularyterm_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_participant_ex_interactionparticipant_id_1a3bbdde" ON "interaction_participant_experimental_roles" USING btree ("interactionparticipant_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_participant_in_controlledvocabularyterm_i_ba68e8dd" ON "interaction_participant_interactor_types" USING btree ("controlledvocabularyterm_id" int4_ops);--> statement-breakpoint
CREATE INDEX "interaction_participant_in_interactionparticipant_id_0b95ae8d" ON "interaction_participant_interactor_types" USING btree ("interactionparticipant_id" int4_ops);--> statement-breakpoint
CREATE INDEX "protein_details_entity_id_1d05a0aa" ON "protein_details" USING btree ("entity_id" int4_ops);--> statement-breakpoint
CREATE INDEX "cv_term_references_controlledvocabularyterm_id_846e2892" ON "cv_term_references" USING btree ("controlledvocabularyterm_id" int4_ops);--> statement-breakpoint
CREATE INDEX "cv_term_references_reference_id_cc691283" ON "cv_term_references" USING btree ("reference_id" int4_ops);--> statement-breakpoint
CREATE INDEX "cv_term_synonym_term_id_e0262e90" ON "cv_term_synonym" USING btree ("term_id" int4_ops);
*/